export const texts = {
    logo: 'Simple-Node-Auth',
    fields: {
        email: 'Email',
        password: 'Password',
        newPassword: 'New password',
        currentEmail: 'Current email',
        name: 'Name',
        age: 'Age',
        operations: 'Operations',
    },
    placeholders: {
        name: 'Enter name',
        age: 'Enter age',
        email: 'Enter email',
        password: 'Enter password',
    },
    titles: {
        auth: 'Welcome!',
        authCard: 'Sign in:',
        main: 'Users',
        edit: 'Edition',
        editCard: 'Change fields:',
        registration: 'Registration',
        registrationCard: 'Fill all fields:',
        reset: 'Reset password',
        resetCard: 'Enter registration email:',
        createCard: 'Create new password:',
        print: 'Users for page ',
    },
    buttons: {
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        download: 'Download',
        print: 'Print',
        login: 'Login',
        register: 'Register',
        delete: 'Delete',
    },
    tips: {
        checkmail: 'After operation check your email in order to reset password',
        remember: 'Remember me',
    },
    links:{
        forgot: 'Forgot password?',
        edit: 'Edit',
        first: 'First',
        last: 'Last',
        page: 'Page',
        users: 'Users',
        add: 'Add user',
        logout: 'Logout',
    },
    icons: {
        arrowDown: 'arrow_drop_down',
        arrowUp: 'arrow_drop_up',
        chevronLeft: 'chevron_left',
        chevronRight: 'chevron_right',
    },
    selects: {
        page1: '3 per page',
        page2: '5 per page',
        page3: '10 per page',
    }
}